title: Khor Shao Liang
description: Software Engineer
author: Khor Shao Liang
github: https://github.com/KhorSL
about: I am a final year student in School of Computing at National University of Singapore. I am pursuing a Bachelor of Computing (Computer Science) specializing in Database Systems.
# disqus_shortname: stackproblems
# google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpeg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/khorshaoliang/"
    # - icon: fa-stack-exchange
    #   link: "#"
    - icon: fa-github
      link: "https://github.com/KhorSL"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: Resume
      url: "https://registry.jsonresume.org/khorsl"
    - text: XML Feed
      url: /feed.xml

url: "https://khorsl.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
